aptly mirror create -architectures=amd64 jp_archive_ubuntu_com_trusty_main http://jp.archive.ubuntu.com/ubuntu/ trusty main
aptly mirror create -architectures=amd64 jp_archive_ubuntu_com_trusty_restricted http://jp.archive.ubuntu.com/ubuntu/ trusty restricted
aptly mirror create -architectures=amd64 jp_archive_ubuntu_com_trusty_universe http://jp.archive.ubuntu.com/ubuntu/ trusty universe
aptly mirror create -architectures=amd64 jp_archive_ubuntu_com_trusty_multiverse http://jp.archive.ubuntu.com/ubuntu/ trusty multiverse
aptly mirror create -architectures=amd64 jp_archive_ubuntu_com_trusty-updates_main http://jp.archive.ubuntu.com/ubuntu/ trusty-updates main
aptly mirror create -architectures=amd64 jp_archive_ubuntu_com_trusty-updates_restricted http://jp.archive.ubuntu.com/ubuntu/ trusty-updates restricted
aptly mirror create -architectures=amd64 jp_archive_ubuntu_com_trusty-updates_universe http://jp.archive.ubuntu.com/ubuntu/ trusty-updates universe
aptly mirror create -architectures=amd64 jp_archive_ubuntu_com_trusty-updates_multiverse http://jp.archive.ubuntu.com/ubuntu/ trusty-updates multiverse
aptly mirror create -architectures=amd64 jp_archive_ubuntu_com_trusty-backports_main http://jp.archive.ubuntu.com/ubuntu/ trusty-backports main
aptly mirror create -architectures=amd64 jp_archive_ubuntu_com_trusty-backports_restricted http://jp.archive.ubuntu.com/ubuntu/ trusty-backports restricted
aptly mirror create -architectures=amd64 jp_archive_ubuntu_com_trusty-backports_universe http://jp.archive.ubuntu.com/ubuntu/ trusty-backports universe
aptly mirror create -architectures=amd64 jp_archive_ubuntu_com_trusty-backports_multiverse http://jp.archive.ubuntu.com/ubuntu/ trusty-backports multiverse
aptly mirror create -architectures=amd64 security_ubuntu_com_trusty-security_main http://security.ubuntu.com/ubuntu trusty-security main
aptly mirror create -architectures=amd64 security_ubuntu_com_trusty-security_restricted http://security.ubuntu.com/ubuntu trusty-security restricted
aptly mirror create -architectures=amd64 security_ubuntu_com_trusty-security_universe http://security.ubuntu.com/ubuntu trusty-security universe
aptly mirror create -architectures=amd64 security_ubuntu_com_trusty-security_multiverse http://security.ubuntu.com/ubuntu trusty-security multiverse
aptly mirror create -architectures=amd64 jp_archive_ubuntu_com_xenial_main http://jp.archive.ubuntu.com/ubuntu/ xenial main
aptly mirror create -architectures=amd64 jp_archive_ubuntu_com_xenial_restricted http://jp.archive.ubuntu.com/ubuntu/ xenial restricted
aptly mirror create -architectures=amd64 jp_archive_ubuntu_com_xenial_universe http://jp.archive.ubuntu.com/ubuntu/ xenial universe
aptly mirror create -architectures=amd64 jp_archive_ubuntu_com_xenial_multiverse http://jp.archive.ubuntu.com/ubuntu/ xenial multiverse
aptly mirror create -architectures=amd64 jp_archive_ubuntu_com_xenial-updates_main http://jp.archive.ubuntu.com/ubuntu/ xenial-updates main
aptly mirror create -architectures=amd64 jp_archive_ubuntu_com_xenial-updates_restricted http://jp.archive.ubuntu.com/ubuntu/ xenial-updates restricted
aptly mirror create -architectures=amd64 jp_archive_ubuntu_com_xenial-updates_universe http://jp.archive.ubuntu.com/ubuntu/ xenial-updates universe
aptly mirror create -architectures=amd64 jp_archive_ubuntu_com_xenial-updates_multiverse http://jp.archive.ubuntu.com/ubuntu/ xenial-updates multiverse
aptly mirror create -architectures=amd64 security_ubuntu_com_xenial-security_main http://security.ubuntu.com/ubuntu xenial-security main
aptly mirror create -architectures=amd64 security_ubuntu_com_xenial-security_restricted http://security.ubuntu.com/ubuntu xenial-security restricted
aptly mirror create -architectures=amd64 security_ubuntu_com_xenial-security_universe http://security.ubuntu.com/ubuntu xenial-security universe
aptly mirror create -architectures=amd64 security_ubuntu_com_xenial-security_multiverse http://security.ubuntu.com/ubuntu xenial-security multiverse
aptly mirror create -architectures=amd64 ppa_launchpad_net_maas_trusty_stable_main http://ppa.launchpad.net/maas/stable/ubuntu/ trusty
aptly mirror create -architectures=amd64 ppa_launchpad_net_maas_xenial_stable_main http://ppa.launchpad.net/maas/stable/ubuntu/ xenial
aptly mirror create -architectures=amd64 ppa_launchpad_net_maas_xenial_proposed_main http://ppa.launchpad.net/maas/proposed/ubuntu/ xenial
aptly mirror create -architectures=amd64 ppa_launchpad_net_juju_trusty_stable_main http://ppa.launchpad.net/juju/stable/ubuntu/ trusty
aptly mirror create -architectures=amd64 ppa_launchpad_net_juju_xenial_stable_main http://ppa.launchpad.net/juju/stable/ubuntu/ xenial
aptly mirror create -architectures=amd64 ubuntu-cloud_archive_canonical_com_xenial-updates_newton_main http://ubuntu-cloud.archive.canonical.com/ubuntu/ xenial-updates/newton main
aptly mirror create -architectures=amd64 ubuntu-cloud_archive_canonical_com_xenial-updates_newton_main http://ubuntu-cloud.archive.canonical.com/ubuntu/ xenial-updates/newton main
aptly mirror create -architectures=amd64 ubuntu-cloud_archive_canonical_com_trusty-updates_mitaka_main http://ubuntu-cloud.archive.canonical.com/ubuntu/ trusty-updates/mitaka main
aptly mirror create -architectures=amd64 ubuntu-cloud_archive_canonical_com_trusty-proposed_mitaka_main http://ubuntu-cloud.archive.canonical.com/ubuntu/ trusty-proposed/mitaka main
aptly repo create -architectures=amd64 -distribution="trusty" -component="main" contrail3.1
